spring : 
    application :
        name: geslic
    output:
        ansi:
            enabled: always        
    datasource: 
        url: jdbc:oracle:thin:@(description= (retry_count=20)(retry_delay=3)(address=(protocol=tcps)(port=1522)(host=adb.eu-madrid-1.oraclecloud.com))(connect_data=(service_name=gcd7eb396eaedf9_geslicdb_low.adb.oraclecloud.com))(security=(ssl_server_dn_match=yes)))
        username: USUARIOGESLIC
        password: Abcdefg12345
        driver-class-name: oracle.jdbc.OracleDriver
    jpa:
        open-in-view: false
