spring : 
    application :
        name: geslic
    output:
        ansi:
            enabled: always        
    jpa:
        properties:
            hibernate:
                "[format_sql]" : true
        
        database-platform: org.hibernate.dialect.OracleDialect
        hibernate:
            ddl-auto: update
        show-sql: true
